[SETUP]

; Spellcross execution mode
run_mode = DOSbox

; Virtual CD drive letter
spellcross_cd_volume = S

; Disable autoexec for DOSbox
DOSbox_no_autoexec = false

; Run in fulscreen in DOSbox
DOSbox_fullscreen = false

; Allow modification of CD game archives
allow_cd_mod = true

; Move save games with the mod
move_mod_saves = true


[PATH]

; Spellcross executable to run
spellcross_executable = SPELCROS.EXE

; Spellcross installation path
spellcross_dir = D:\Hry\spelcros_temp
spellcross_dir<1> = D:\Hry\Spellcross
spellcross_dir<2> = D:\Hry\SPELCROS
spellcross_dir<3> = 
spellcross_dir<4> = 
spellcross_dir<5> = 
spellcross_dir<6> = 
spellcross_dir<7> = 
spellcross_dir<8> = 
spellcross_dir<9> = 

; Spellcross CD copy path (if applicable)
spellcross_cd_dir = D:\Hry\spellcd_temp
spellcross_cd_dir<1> = D:\Hry\spellcd
spellcross_cd_dir<2> = 
spellcross_cd_dir<3> = 
spellcross_cd_dir<4> = 
spellcross_cd_dir<5> = 
spellcross_cd_dir<6> = 
spellcross_cd_dir<7> = 
spellcross_cd_dir<8> = 
spellcross_cd_dir<9> = 

; DOSbox executable path (if exist)
dosbox_path = D:\Program Files\DOSBox-0.74\DOSBox.exe
dosbox_path<1> = 
dosbox_path<2> = 
dosbox_path<3> = 
dosbox_path<4> = 
dosbox_path<5> = 
dosbox_path<6> = 
dosbox_path<7> = 
dosbox_path<8> = 
dosbox_path<9> = 

; Spellcross mod path
mod_path = D:\Hry\SPELCROS\MOD\aliance_cz\config.def
mod_path<1> = 
mod_path<2> = 
mod_path<3> = 
mod_path<4> = 
mod_path<5> = 
mod_path<6> = 
mod_path<7> = 
mod_path<8> = 
mod_path<9> = 
