[SETUP]

; Enable logger?
enable_log_file = 0

; Spellcross execution mode
run_mode = DOSbox

; Virtual CD drive letter
spellcross_cd_volume = S

; Disable autoexec for DOSbox
DOSbox_no_autoexec = false

; Run in fulscreen in DOSbox
DOSbox_fullscreen = false

; Allow modification of CD game archives
allow_cd_mod = true

; Move save games with the mod
move_mod_saves = true

; Allow units randomization
allow_units_randomize = true

; Units randomization
units_randomize = 1


[PATH]

; Last units randomize preset
units_randomizer_preset = F:\Data\C\_msvc_\spellcross-mod-launcher\builds\x64\Debug\randomizer\basic.ini

; Spellcross executable to run
spellcross_executable = SPELCROS.EXE

; Spellcross installation path
spellcross_dir = D:\Hry\spelleng
spellcross_dir<1> = D:\Hry\SPELCROS
spellcross_dir<2> = D:\Hry\Spellcross
spellcross_dir<3> = D:\Hry\spelcros_temp
spellcross_dir<4> = 
spellcross_dir<5> = 
spellcross_dir<6> = 
spellcross_dir<7> = 
spellcross_dir<8> = 
spellcross_dir<9> = 

; Spellcross CD copy path (if applicable)
spellcross_cd_dir = D:\Hry\spelleng_cd
spellcross_cd_dir<1> = D:\Hry\spelleng_cd\DATA
spellcross_cd_dir<2> = D:\Hry\Spellcross
spellcross_cd_dir<3> = D:\Hry\spellcd_temp
spellcross_cd_dir<4> = D:\Hry\spellcd
spellcross_cd_dir<5> = 
spellcross_cd_dir<6> = 
spellcross_cd_dir<7> = 
spellcross_cd_dir<8> = 
spellcross_cd_dir<9> = 

; DOSbox executable path (if exist)
dosbox_path = D:\Program Files\DOSBox-0.74\DOSBox.exe
dosbox_path<1> = 
dosbox_path<2> = 
dosbox_path<3> = 
dosbox_path<4> = 
dosbox_path<5> = 
dosbox_path<6> = 
dosbox_path<7> = 
dosbox_path<8> = 
dosbox_path<9> = 

; Spellcross mod path
mod_path = D:\Hry\SPELCROS\MOD\Spellcross-Mod-CZ-Hard\mod\config.def
mod_path<1> = D:\Hry\SPELCROS\MOD\Spellcross-Mod-CZ-Hard\mod2\config.def
mod_path<2> = D:\Hry\SPELCROS\MOD\Spellcross-Mod-CZ-Hard\builds\spellcross-mod-cz-hard\config.def
mod_path<3> = D:\Hry\SPELCROS\MOD\mod_units\config.def
mod_path<4> = D:\Hry\SPELCROS\MOD\test_cz\config.def
mod_path<5> = D:\Hry\SPELCROS\MOD\videos_cz\config.def
mod_path<6> = D:\Hry\SPELCROS\MOD\aliance_cz\config.def
mod_path<7> = 
mod_path<8> = 
mod_path<9> = 


[STATE]
win_x_size = 900
win_y_size = 828
win_maximize = false
