
#include "SpellLaunch.h"
#include <string>
#include "other.h"

const std::string SpellLaunch::box_exec_name = "box_exec.bat";
const std::string SpellLaunch::box_setup_name = "box_set.bat";
const std::string SpellLaunch::run_dosbox_name = "run_DOSbox.bat";
const std::string SpellLaunch::setup_dosbox_name = "setup_DOSbox.bat";
const std::string SpellLaunch::run_win32_name = "run_Win32.bat";
const std::string SpellLaunch::setup_win32_name = "SETUP.bat";

// run game
int SpellLaunch::RunGame(std::filesystem::path spell_dir, std::string run_mode, std::function<void(std::string)> console_cb)
{    
    if(console_cb)
        console_cb("Running game ... \n");

    // select run mode
    std::string batch_name = "";
    if(run_mode == "DOSbox")
        batch_name = run_dosbox_name;
    else if(run_mode == "Win32")
        batch_name = run_win32_name;
    if(batch_name.empty())
    {
        if(console_cb)
            console_cb(" - failed! Unknown run mode.\n");
        return(1);
    }

    // get spellcross path
    if(spell_dir.empty())
    {
        if(console_cb)
            console_cb(" - failed! Spellcross directory not selected.\n");
        return(1);
    }
    auto batch_path = spell_dir / std::filesystem::path(batch_name);

    //std::string command = string_format("START \"Spellcross launcher\" /D \"%ls\" /WAIT \"cmd /C \"%s\" \"",spell_dir.c_str(), batch_name.c_str());
    std::string command = string_format("START \"Spellcross Mod Build by Stanislav Maslan\" /D \"%ls\" /WAIT \"%s\"",spell_dir.c_str(),batch_name.c_str());
    std::system(command.c_str());

    if(console_cb)
        console_cb(" - Done!\n");
    
    return(0);
}

// run game
int SpellLaunch::RunSetup(std::filesystem::path spell_dir,std::string run_mode,std::function<void(std::string)> console_cb)
{
    if(console_cb)
        console_cb("Running game SETUP ... \n");

    // select run mode
    std::string batch_name = "";
    if(run_mode == "DOSbox")
        batch_name = setup_dosbox_name;
    else if(run_mode == "Win32")
        batch_name = setup_win32_name;
    if(batch_name.empty())
    {
        if(console_cb)
            console_cb(" - failed! Unknown run mode.\n");
        return(1);
    }

    // get spellcross path
    if(spell_dir.empty())
    {
        if(console_cb)
            console_cb(" - failed! Spellcross directory not selected.\n");
        return(1);
    }
    auto batch_path = spell_dir / std::filesystem::path(batch_name);

    //std::string command = string_format("START \"Spellcross launcher\" /D \"%ls\" /WAIT \"cmd /C \"%s\" \"",spell_dir.c_str(), batch_name.c_str());
    std::string command = string_format("START \"Spellcross Mod Build by Stanislav Maslan\" /D \"%ls\" /WAIT \"%s\"",spell_dir.c_str(),batch_name.c_str());
    std::system(command.c_str());

    if(console_cb)
        console_cb(" - Done!\n");

    return(0);
}



// make SPELCROS.CD file with drive letter
int SpellLaunch::MakeSpellCD(std::filesystem::path spell_dir,std::string drive)
{
    if(drive.size() != 1)
        return(1);
    auto path = spell_dir / "SPELCROS.CD";
    std::string old;
    if(loadstr(path.wstring(),old) || old != drive)
        savestr(path.wstring(),toupper(drive));
    return(0);
}

// make DOSbox batch file: the one to be executed within DOSbox to launch the game setup
int SpellLaunch::MakeSpellDOSboxSetupBat(std::filesystem::path spell_dir)
{
    auto path = spell_dir / box_setup_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to run Spellcross SETUP inside DOSbox ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)   ---\n\n");

    bat += string_format("rem --- run Spellcross SETUP ---\n");
    bat += string_format("@ECHO Starting Spellcross SETUP ...\n");
    bat += string_format("CALL SETUP.BAT\n\n");

    bat += string_format("rem--- finito---\n");
    bat += string_format("exit\n");

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make DOSbox batch file: the one to be executed within DOSbox to launch the game
int SpellLaunch::MakeSpellDOSboxExecBat(std::filesystem::path spell_dir,std::filesystem::path spellcd_dir,std::string drive,std::string spell_exe)
{
    auto path = spell_dir / box_exec_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to run Spellcross game inside DOSbox ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)  ---\n\n");

    bat += string_format("rem --- Spellcross executable name ---\n");
    bat += string_format("SET EXENAME=%s\n\n",spell_exe.c_str());

    // mount CD optionally only if CD path defined
    if(!spellcd_dir.empty())
    {
        if(drive.size() != 1)
            return(1);
        bat += string_format("rem--- Spellcross CD content folder---\n");
        bat += string_format("SET SPELLCD=%ls\n\n",spellcd_dir.wstring().c_str());

        bat += string_format("rem--- mount Spellcross CD drive from folder---\n");
        bat += string_format("@ECHO Mounting virtual CD drive %s ...\n",drive.c_str());
        bat += string_format("mount %s \"%%SPELLCD%%\" -t cdrom\n\n",drive.c_str());
    }

    bat += string_format("rem--- run Spellcross---\n");
    bat += string_format("@ECHO Starting Spellcross ...\n");
    bat += string_format("%%EXENAME%%\n\n");

    bat += string_format("rem--- finito---\n");
    bat += string_format("exit\n");

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make DOSbox batch file: the one that starts DOSbox and launches the game inside
int SpellLaunch::MakeSpellDOSboxRunBat(std::filesystem::path spell_dir,std::filesystem::path dosbox_path,bool no_autoexec,bool fullscreen)
{
    auto path = spell_dir / run_dosbox_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to start DOSbox and run Spellcross game inside ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)            ---\n\n");

    bat += string_format("rem --- DOXbox path ---\n");
    bat += string_format("SET DOSBOX=%ls\n\n",dosbox_path.wstring().c_str());

    bat += string_format("rem --- Launch Spellcross through DOSbox ---\n");
    bat += string_format("@ECHO Starting Spellcross in DOSbox ...\n");
    bat += string_format("cmd /C \"%%DOSBOX%%\" %s",box_exec_name.c_str());
    if(no_autoexec)
        bat += " -noautoexec";
    if(fullscreen)
        bat += " -fullscreen";
    bat += "\n";

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make DOSbox batch file: the one that starts DOSbox and launches the game SETUP inside
int SpellLaunch::MakeSpellDOSboxRunSetupBat(std::filesystem::path spell_dir,std::filesystem::path dosbox_path)
{
    auto path = spell_dir / setup_dosbox_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to start DOSbox and run Spellcross game SETUP inside ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)                  ---\n\n");

    bat += string_format("rem --- DOXbox path ---\n");
    bat += string_format("SET DOSBOX=%ls\n\n",dosbox_path.wstring().c_str());

    bat += string_format("rem --- Launch Spellcross SETUP through DOSbox ---\n");
    bat += string_format("@ECHO Starting Spellcross SETUP in DOSbox ...\n");
    bat += string_format("cmd /C \"%%DOSBOX%%\" %s -noautoexec\n",box_setup_name.c_str());

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make Win32 batch file: the one that starts DOSbox and launches the game inside
int SpellLaunch::MakeSpellWin32RunBat(std::filesystem::path spell_dir,std::filesystem::path spellcd_dir,std::string drive,std::string spell_exe)
{
    auto path = spell_dir / run_win32_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to run Spellcross on Win32 natively ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher) ---\n\n");

    bat += string_format("rem --- Spellcross executable name ---\n");
    bat += string_format("SET EXENAME=%s\n\n",spell_exe.c_str());

    if(!spellcd_dir.empty())
    {
        if(drive.empty())
            return(1);

        bat += string_format("rem --- Spellcross CD content folder ---\n");
        bat += string_format("SET SPELLCD=%ls\n\n",spellcd_dir.wstring().c_str());

        bat += string_format("rem --- Create virtual drive from Spellcross CD folder ---\n");
        bat += string_format("@ECHO Mounting virtual drive %s ...\n",drive.c_str());
        bat += string_format("subst %s: \"%%SPELLCD%%\"\n\n",drive.c_str());
    }

    bat += string_format("rem --- Run Spellcross---\n");
    bat += string_format("@ECHO Starting Spellcross ...\n");
    bat += string_format("IF(%%OS%%)==(Windows_NT) GOTO WinNT\n");
    bat += string_format("START /WAIT command /C %%EXENAME%%\n");
    bat += string_format("GOTO Win98\n");
    bat += string_format(":WinNT\n");
    bat += string_format("START \"Spellcross Launcher by Stanislav Maslan\" /D \"%%CD%%\" /WAIT \"cmd /C \"%%EXENAME%%\" \"\n");
    bat += string_format(":Win98\n\n");

    if(!spellcd_dir.empty())
    {
        bat += string_format("rem --- Unmount virtual drive ---\n");
        bat += string_format("@ECHO Unmounting virtual drive %s ...\n",drive.c_str());
        bat += string_format("subst %s: /D\n",drive.c_str());
    }

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}
