
#include "SpellLaunch.h"
#include <string>
#include <chrono>
#include <map>
#include "other.h"

const std::string SpellLaunch::box_exec_name = "box_exec.bat";
const std::string SpellLaunch::box_setup_name = "box_set.bat";
const std::string SpellLaunch::run_dosbox_name = "run_DOSbox.bat";
const std::string SpellLaunch::setup_dosbox_name = "setup_DOSbox.bat";
const std::string SpellLaunch::run_win32_name = "run_Win32.bat";
const std::string SpellLaunch::setup_win32_name = "SETUP.bat";
std::string SpellLaunch::m_last_error;

// run game
int SpellLaunch::RunGame(std::filesystem::path spell_dir, std::string run_mode, std::function<void(std::string)> console_cb)
{    
    if(console_cb)
        console_cb("Running game ... \n");      

    // select run mode
    std::string batch_name = "";
    if(run_mode == "DOSbox")
        batch_name = run_dosbox_name;
    else if(run_mode == "Win32")
        batch_name = run_win32_name;
    if(batch_name.empty())
    {
        if(console_cb)
            console_cb(" - failed! Unknown run mode.\n");
        return(1);
    }

    // get spellcross path
    if(spell_dir.empty())
    {
        if(console_cb)
            console_cb(" - failed! Spellcross directory not selected.\n");
        return(1);
    }
    auto batch_path = spell_dir / std::filesystem::path(batch_name);

    //std::string command = string_format("START \"Spellcross launcher\" /D \"%ls\" /WAIT \"cmd /C \"%s\" \"",spell_dir.c_str(), batch_name.c_str());
    std::string command = string_format("START \"Spellcross Mod Build by Stanislav Maslan\" /D \"%ls\" /WAIT \"%s\"",spell_dir.c_str(),batch_name.c_str());
    std::system(command.c_str());

    if(console_cb)
        console_cb(" - Done!\n");
    
    return(0);
}

// run game
int SpellLaunch::RunSetup(std::filesystem::path spell_dir,std::string run_mode,std::function<void(std::string)> console_cb)
{
    if(console_cb)
        console_cb("Running game SETUP ... \n");

    // select run mode
    std::string batch_name = "";
    if(run_mode == "DOSbox")
        batch_name = setup_dosbox_name;
    else if(run_mode == "Win32")
        batch_name = setup_win32_name;
    if(batch_name.empty())
    {
        if(console_cb)
            console_cb(" - failed! Unknown run mode.\n");
        return(1);
    }

    // get spellcross path
    if(spell_dir.empty())
    {
        if(console_cb)
            console_cb(" - failed! Spellcross directory not selected.\n");
        return(1);
    }
    auto batch_path = spell_dir / std::filesystem::path(batch_name);

    //std::string command = string_format("START \"Spellcross launcher\" /D \"%ls\" /WAIT \"cmd /C \"%s\" \"",spell_dir.c_str(), batch_name.c_str());
    std::string command = string_format("START \"Spellcross Mod Build by Stanislav Maslan\" /D \"%ls\" /WAIT \"%s\"",spell_dir.c_str(),batch_name.c_str());
    std::system(command.c_str());

    if(console_cb)
        console_cb(" - Done!\n");

    return(0);
}



// make SPELCROS.CD file with drive letter
int SpellLaunch::MakeSpellCD(std::filesystem::path spell_dir,std::string drive)
{
    if(drive.size() != 1)
        return(1);
    auto path = spell_dir / "SPELCROS.CD";
    std::string old;
    if(loadstr(path.wstring(),old) || old != drive)
        savestr(path.wstring(),toupper(drive));
    return(0);
}

// make DOSbox batch file: the one to be executed within DOSbox to launch the game setup
int SpellLaunch::MakeSpellDOSboxSetupBat(std::filesystem::path spell_dir)
{
    auto path = spell_dir / box_setup_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to run Spellcross SETUP inside DOSbox ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)   ---\n\n");

    bat += string_format("rem --- run Spellcross SETUP ---\n");
    bat += string_format("@ECHO Starting Spellcross SETUP ...\n");
    bat += string_format("IF NOT EXIST SETUP.BAT GOTO ENG\n");
    bat += string_format("CALL SETUP.BAT\n");
    bat += string_format("exit\n");
    bat += string_format(":ENG\n");
    bat += string_format("CALL SETSOUND.BAT\n\n");

    bat += string_format("rem --- finito---\n");
    bat += string_format("exit\n");

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make DOSbox batch file: the one to be executed within DOSbox to launch the game
int SpellLaunch::MakeSpellDOSboxExecBat(std::filesystem::path spell_dir,std::filesystem::path spellcd_dir,std::string drive,std::string spell_exe)
{
    auto path = spell_dir / box_exec_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to run Spellcross game inside DOSbox ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)  ---\n\n");

    bat += string_format("rem --- Spellcross executable name ---\n");
    bat += string_format("SET EXENAME=%s\n\n",spell_exe.c_str());

    // mount CD optionally only if CD path defined
    if(!spellcd_dir.empty())
    {
        if(drive.size() != 1)
            return(1);
        bat += string_format("rem--- Spellcross CD content folder---\n");
        bat += string_format("SET SPELLCD=%ls\n\n",spellcd_dir.wstring().c_str());

        bat += string_format("rem--- mount Spellcross CD drive from folder---\n");
        bat += string_format("@ECHO Mounting virtual CD drive %s ...\n",drive.c_str());
        bat += string_format("mount %s \"%%SPELLCD%%\" -t cdrom\n\n",drive.c_str());
    }

    bat += string_format("rem--- run Spellcross---\n");
    bat += string_format("@ECHO Starting Spellcross ...\n");
    bat += string_format("%%EXENAME%%\n\n");

    bat += string_format("rem--- finito---\n");
    bat += string_format("exit\n");

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make DOSbox batch file: the one that starts DOSbox and launches the game inside
int SpellLaunch::MakeSpellDOSboxRunBat(std::filesystem::path spell_dir,std::filesystem::path dosbox_path,bool no_autoexec,bool fullscreen)
{
    auto path = spell_dir / run_dosbox_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to start DOSbox and run Spellcross game inside ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)            ---\n\n");

    bat += string_format("rem --- DOXbox path ---\n");
    bat += string_format("SET DOSBOX=%ls\n\n",dosbox_path.wstring().c_str());

    bat += string_format("rem --- Launch Spellcross through DOSbox ---\n");
    bat += string_format("@ECHO Starting Spellcross in DOSbox ...\n");
    bat += string_format("cmd /C \"%%DOSBOX%%\" %s",box_exec_name.c_str());
    if(no_autoexec)
        bat += " -noautoexec";
    if(fullscreen)
        bat += " -fullscreen";
    bat += "\n";

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make DOSbox batch file: the one that starts DOSbox and launches the game SETUP inside
int SpellLaunch::MakeSpellDOSboxRunSetupBat(std::filesystem::path spell_dir,std::filesystem::path dosbox_path)
{
    auto path = spell_dir / setup_dosbox_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to start DOSbox and run Spellcross game SETUP inside ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher)                  ---\n\n");

    bat += string_format("rem --- DOXbox path ---\n");
    bat += string_format("SET DOSBOX=%ls\n\n",dosbox_path.wstring().c_str());

    bat += string_format("rem --- Launch Spellcross SETUP through DOSbox ---\n");
    bat += string_format("@ECHO Starting Spellcross SETUP in DOSbox ...\n");
    bat += string_format("cmd /C \"%%DOSBOX%%\" %s -noautoexec\n",box_setup_name.c_str());

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}

// make Win32 batch file: the one that starts DOSbox and launches the game inside
int SpellLaunch::MakeSpellWin32RunBat(std::filesystem::path spell_dir,std::filesystem::path spellcd_dir,std::string drive,std::string spell_exe)
{
    auto path = spell_dir / run_win32_name;
    std::string bat;
    bat += string_format("@ECHO OFF\n\n");
    bat += string_format("rem --- Script to run Spellcross on Win32 natively ---\n");
    bat += string_format("rem --- (autogenerated by Spellcross Mod Launcher) ---\n\n");

    bat += string_format("rem --- Spellcross executable name ---\n");
    bat += string_format("SET EXENAME=%s\n\n",spell_exe.c_str());

    if(!spellcd_dir.empty())
    {
        if(drive.empty())
            return(1);

        bat += string_format("rem --- Spellcross CD content folder ---\n");
        bat += string_format("SET SPELLCD=%ls\n\n",spellcd_dir.wstring().c_str());

        bat += string_format("rem --- Create virtual drive from Spellcross CD folder ---\n");
        bat += string_format("@ECHO Mounting virtual drive %s ...\n",drive.c_str());
        bat += string_format("subst %s: \"%%SPELLCD%%\"\n\n",drive.c_str());
    }

    bat += string_format("rem --- Run Spellcross---\n");
    bat += string_format("@ECHO Starting Spellcross ...\n");
    bat += string_format("IF(%%OS%%)==(Windows_NT) GOTO WinNT\n");
    bat += string_format("START /WAIT command /C %%EXENAME%%\n");
    bat += string_format("GOTO Win98\n");
    bat += string_format(":WinNT\n");
    bat += string_format("START \"Spellcross Launcher by Stanislav Maslan\" /D \"%%CD%%\" /WAIT \"cmd /C \"%%EXENAME%%\" \"\n");
    bat += string_format(":Win98\n\n");

    if(!spellcd_dir.empty())
    {
        bat += string_format("rem --- Unmount virtual drive ---\n");
        bat += string_format("@ECHO Unmounting virtual drive %s ...\n",drive.c_str());
        bat += string_format("subst %s: /D\n",drive.c_str());
    }

    std::string bat_old;
    if(loadstr(path,bat_old) || bat_old != bat)
        savestr(path,bat);

    return(0);
}



// try idnetify game engine version from EXE file
int SpellLaunch::GameEngineVersion(std::filesystem::path spell_dir, std::string spell_exe, SpellLaunch::GameVersion &ver)
{
    ver = {EngineVersion::NONE, ExeVersion::UNKNOWN, "Unknown", 0};

    auto exe_path = spell_dir / spell_exe;
    if(!std::filesystem::exists(exe_path))
        return(1);
    
    std::vector<uint8_t> data;
    if(loaddata(exe_path,data))
        return(1);
     
    // calc EXE hash
    std::hash<std::string> hash;
    std::string str(data.begin(),data.end());
    auto exe_hash = hash(str);

    // try to match known versions
    const std::vector<GameVersion> ver_list = {
        {EngineVersion::ENG, ExeVersion::EN_100, "English (initial release)", 17968204797226898554},
        {EngineVersion::ENG, ExeVersion::EN_101, "English (patch V1.01)", 260851315303727605},
        {EngineVersion::ENG, ExeVersion::EN_CRACK, "English (unknown no-cd patch)", 4795372327937121801},
        {EngineVersion::CZE, ExeVersion::CZ_100, "Czech (initial release)", 5049612772850811613},
        {EngineVersion::CZE, ExeVersion::CZ_106, "Czech (patch V1.06)", 18295206956031377920},
        {EngineVersion::CZE, ExeVersion::CZ_107, "Czech (patch V1.07)", 5526712442606542630}
    };    
    for(auto &item: ver_list)
        if(item.exe_hash == exe_hash)
        {
            ver = item;
            break;
        }   
    
    if(ver.engine_ver != EngineVersion::NONE)
        return(0);

    // try crude check if it's czech or english
    std::string key = "Smacker Video Technology.";
    std::vector<uint8_t> bin(key.begin(), key.end());    
    if(std::search(data.begin(), data.end(), key.begin(), key.end()) != data.end())
    {
        ver.engine_ver = EngineVersion::ENG;
        ver.version_name = "English (unknown version)";
        return(0);
    }
    key = "SPELLCROSS: Posledn";
    bin.assign(key.begin(),key.end());
    if(std::search(data.begin(),data.end(),key.begin(),key.end()) != data.end())
    {
        ver.engine_ver = EngineVersion::CZE;
        ver.version_name = "Czech (unknown version)";
    }

    return(0);
}

// try patch spellcross exe
int SpellLaunch::PatchExe(std::filesystem::path spell_dir,std::string spell_exe, bool check_only, std::string backup_name)
{
    m_last_error = "";

    // check version
    GameVersion ver;
    if(GameEngineVersion(spell_dir, spell_exe, ver))
    {
        m_last_error = string_format("Patching EXE failed! Failed recognition of %s version.",spell_exe.c_str());
        return(1);
    }

    std::vector<std::pair<uint32_t,uint8_t>> patch;
    if(ver.exe_version == ExeVersion::EN_100)
    {
        // patch from EN V1.00
        patch= {
            {0x0A53C5, 0x90},
            {0x0A53C6, 0x90},
            {0x0D4BE0, 0xEB},
            {0x0D4BF6, 0x90},
            {0x0D4BF7, 0x90},
            {0x0D5073, 0xEB},
            {0x0D5089, 0x90},
            {0x0D508A, 0x90},
            {0x0F21BD, 0xB8},
            {0x0F21BE, 0x07},
            {0x0F21BF, 0x00},
            {0x0F21C0, 0x00},
            {0x0F21C1, 0x00},
            {0x0F21C2, 0xC3}        
        };
    }
    else if(ver.exe_version == ExeVersion::EN_101)
    {
        // patch from EN V1.01
        patch = {
            {0x0422D8, 0x74},
            {0x0433F8, 0x74},
            {0x043420, 0x75},
            {0x043421, 0xBE},        
            {0x0A53C5, 0x90},
            {0x0A53C6, 0x90},
            {0x0D4BE0, 0xEB},
            {0x0D4BF6, 0x90},
            {0x0D4BF7, 0x90},
            {0x0D5073, 0xEB},
            {0x0D5089, 0x90},
            {0x0D508A, 0x90},
            {0x0F21BD, 0xB8},
            {0x0F21BE, 0x07},
            {0x0F21BF, 0x00},
            {0x0F21C0, 0x00},
            {0x0F21C1, 0x00},
            {0x0F21C2, 0xC3}
        };
    }
    else if(ver.exe_version == ExeVersion::EN_CRACK)
    {
        // patch/crack?
        m_last_error = "Patching EXE not supported for this game version - this is already patched version!";
        return(1);
    }
    else
    {
        m_last_error = "Patching EXE not supported for this game version!";
        return(1);
    }
    if(check_only)
        return(0);

    // load original
    auto exe_path = spell_dir / spell_exe;
    if(!std::filesystem::exists(exe_path))
    {
        m_last_error = string_format("Patching SPELCROS.EXE failed! Path \"%ls\" does not exist.", exe_path.wstring().c_str());
        return(1);
    }
    std::vector<uint8_t> data;
    if(loaddata(exe_path,data))
    {
        m_last_error = string_format("Patching SPELCROS.EXE failed! Reading \"%ls\" failed.",exe_path.wstring().c_str());
        return(1);
    }

    // check EXE hash
    std::hash<std::string> hash;
    std::string str(data.begin(),data.end());
    auto exe_hash = hash(str);
    if(exe_hash != ver.exe_hash)
    {
        m_last_error = string_format("Patching SPELCROS.EXE failed! Hash of \"%ls\" does not match known supported versions.",exe_path.wstring().c_str());
        return(1);
    }

    // make backup
    auto bak_path = spell_dir / backup_name;
    if(fs_copy(exe_path,bak_path,std::filesystem::copy_options::overwrite_existing))
    {
        m_last_error = string_format("Patching SPELCROS.EXE failed! Making backup of \"%ls\" to \"%ls\" failed.",exe_path.wstring().c_str(),bak_path.wstring().c_str());
        return(1);
    }

    // patch EXE
    for(auto &item: patch)
    {
        if(item.first >= data.size())
        {
            m_last_error = string_format("Patching of \"%ls\" failed (write beyond end of file)!",exe_path.wstring().c_str());
            return(1);
        }
        data[item.first] = item.second;
    }

    // try save
    if(savedata(exe_path, data))
    {
        m_last_error = string_format("Patching SPELCROS.EXE failed! Saving modified \"%ls\" failed.",exe_path.wstring().c_str());
        return(1);
    }

    return(0);
}